language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"

matrix:
  allow_failures:
    - perl: "5.20"

env:
  global:
    # Carton --deployment only works on the same version of perl
    # that the snapshot was built from.
    - DEPLOYMENT_PERL_VERSION=5.18

before_install:
  - npm install -g less js-beautify
  # Pre-install from backpan to avoid upgrade breakage.
  - cpanm -n http://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/common-sense-3.6.tar.gz
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n Carton

install:
  # Carton::Builder (carton install) passes --notest to cpanm.
  - 'carton install `test "${TRAVIS_PERL_VERSION}" = "${DEPLOYMENT_PERL_VERSION}" && echo " --deployment"`'


script:
  # Devel::Cover isn't in the cpanfile
  # but if it's installed into the global dirs this should work.
  - HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,local carton exec prove -lrv t

after_success:
  - cover -report coveralls


notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: change
    on_failure: always
  irc: "irc.perl.org#metacpan-travis"

# Use newer travis infrastructure.
sudo: false
