excludes = [
    ".build/**",
    "blib/**",
]

[commands.perlimports]
type = "both"
include = [ "**/*.{pl,pm,t,psgi}" ]
cmd = [ "perlimports" ]
lint-flags = ["--lint" ]
tidy-flags = ["-i" ]
ok-exit-codes = 0
expect-stderr = true

[commands.perlcritic]
type = "lint"
include = [ "**/*.{pl,pm,t,psgi}" ]
cmd = [ "perlcritic", "--profile=$PRECIOUS_ROOT/.perlcriticrc" ]
ok-exit-codes = 0
lint-failure-exit-codes = 2

[commands.perltidy]
type = "both"
include = [ "**/*.{pl,pm,t,psgi}" ]
cmd = [ "perltidy", "--profile=$PRECIOUS_ROOT/.perltidyrc" ]
lint-flags = [ "--assert-tidy", "--no-standard-output", "--outfile=/dev/null" ]
tidy-flags = [ "--backup-and-modify-in-place", "--backup-file-extension=/" ]
ok-exit-codes = 0
lint-failure-exit-codes = 2
ignore-stderr = "Begin Error Output Stream"

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = [ "omegasort", "--sort", "path", "--unique" ]
lint-flags = "--check"
tidy-flags = "--in-place"
ok-exit-codes = 0
lint-failure-exit-codes = 1
ignore-stderr = [
    "The .+ file is not sorted",
    "The .+ file is not unique",
]

[commands.prettier-markdown]
type    = "both"
include = "**/*.md"
cmd     = [
    "./node_modules/.bin/prettier",
    "--no-config",
    "--print-width", "100",
    "--prose-wrap", "always",
]
lint-flags = "--check"
tidy-flags = "--write"
ok-exit-codes = 0
lint-failure-exit-codes = 1
ignore-stderr = [ "Code style issues" ]

[commands.prettier-yaml]
type    = "both"
include = "**/*.yml"
cmd     = [
    "./node_modules/.bin/prettier",
    "--no-config",
    "--single-quote",
]
lint-flags = "--check"
tidy-flags = "--write"
ok-exit-codes = 0
lint-failure-exit-codes = 1
ignore-stderr = [ "Code style issues" ]
