name: Upload Coverage Report

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: codecov.json
          id: ${{ github.event.workflow_run.id }}
      - uses: actions/checkout@v4
        name: Checkout codecov.yml
        with:
          path: repo
          sparse-checkout: |
            codecov.yml
          sparse-checkout-cone-mode: false
      - uses: actions/github-script@v7
        name: Find associated pull request
        id: pr
        with:
          script: |
            const response = await github.rest.search.issuesAndPullRequests({
              q: 'repo:${{ github.repository }} is:pr sha:${{ github.event.workflow_run.head_sha }}',
              per_page: 1,
            })
            const items = response.data.items
            if (items.length < 1) {
              console.error('No PRs found')
              return
            }
            const pullRequest = items[0]
            console.info("Pull request number is", pullRequest.number)
            return pullRequest
      - name:
        env:
          PR_DATA: ${{ steps.id.outputs.result }}
          EVENT_DATA: ${{ toJson(github.event) }}
        run: 'printf "pr:\n%s\nevent:\n%s\n" "$PR_DATA" "$EVENT_DATA"'
#      - uses: codecov/codecov-action@v4
#        if: hashFiles('codecov.json')
#        with:
#          codecov_yml_path: repo/codecov.yml
#          disable_search: true
#          file: codecov.json
#          token: ${{ secrets.CODECOV_TOKEN }}
#          commit_parent: ${{  }}
#          job_code: ${{ github.event.workflow.name }}
#          os: ${{ }}
#          override_branch: ${{ }}
#          override_build: ${{ }}
#          override_build_url: ${{ }}
#          override_commit: ${{ }}
#          override_pr: ${{ }}
